frame_id: /map
planner_rate: 0.5
#map params
size_x: 1200
size_y: 700
size_z: 50
origin_x: -35.025
origin_y: -12.025
origin_z: 0.0
resolution: 0.10

#topic name params
goal_topic: /robot_goals
map_topic: /merged_map 
pose_topic: /robot_poses

#cost params
#objectmaxelev: 
#obsvalue: 
#freevalue: 
#unkvalue: 
#numangles:
#mindist: 

robot_params: [
    {
        name: "segbot",
        motionheight: 0.0,
        sensorheight: 0.5,
        horizontalfov_degs: 22.5,
        verticalfov_degs: 18.0,
        detectionrange: 5.0,
        circularsize: 1.0
    },
    {
        name: "hexa",
        motionheight: 1.2,
        sensorheight: 1.2,
        horizontalfov_degs: 22.5,
        verticalfov_degs: 18.0,
        detectionrange: 5.0,
        circularsize: 1.0
    }
]
